# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push
default_stages:
  - pre-commit
exclude: >-
  (?x)^(
    .*\.(patch|diff)$
    |.*/postgres/introspect/.*\.json$
    |rbe/auth/.*\.json$
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: >-
          (?x)^(
            build/docs/.*/.*\.md
          )$
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt
  - repo: https://github.com/crate-ci/typos
    rev: v1.32.0
    hooks:
      - id: typos
        args: [--config, .typos.toml]
        exclude: >-
          (?x)^(
            ^\.typos\.toml$
          )$
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: [--fix]
        exclude: >-
          (?x)^(
            build/docs/.*/.*\.md
          )$
  - repo: https://github.com/mpalmer/action-validator
    rev: v0.7.1
    hooks:
      - id: action-validator
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        name: ruff-check
        args: [--config, .ruff.toml, --fix]
      - id: ruff-format
        args: [--config, .ruff.toml]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: [--enable=all]
  - repo: https://github.com/mrtazz/checkmake.git
    rev: 0.2.2
    hooks:
      - id: checkmake
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 7.3.1.1
    hooks:
      - id: buildifier
        args: &args
          - --warnings=all
      - id: buildifier-lint
        args: *args
  - repo: https://github.com/waisbrot/pre-commit-jsonnet.git
    rev: v1.0
    hooks:
      - id: jsonnetfmt
  - repo: local
    hooks:
      - id: bazel-test
        name: bazel-test
        entry: cd build && bazel test //...
        language: system
        pass_filenames: false
        verbose: false
        stages: [manual]
