preview = true
lint.select = ["ALL"]
lint.fixable = ["ALL"]
lint.ignore = [
    "T201",  # `print` found
    "DTZ005",  # `datetime.datetime.now()` without TZ
    "D",  # # Missing docstring in public {method,class,function,package}
    "DOC201",  # `return` is not documented in docstring
    "CPY001",  # Missing copyright notice at top of file
]
