apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jjmaestro@ieee.org
    profile: tlsserver
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          route53:
            auth:
              kubernetes:
                serviceAccountRef:
                  name: cert-manager
            region: eu-west-2
            role: arn:aws:iam::857517990941:role/cert-manager-route53-rbe.monogres.dev
